In [1]:
import numpy as np

#### Fast way to create a list of integers instead of using FOR

In [3]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#### Create array filled with zeros

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [8]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

#### Shift elements in the array horizontally

In [9]:
a = np.arange(10)

In [10]:
np.roll(a, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.roll(a, -2)

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [21]:
b = np.reshape(a, (5, 2))

In [22]:
np.roll(b, 1)

array([[9, 0],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
np.roll(b, 1, axis=0) # move downwards

array([[8, 9],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
np.roll(b, 1, axis=1) # move among columns

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6],
       [9, 8]])

#### if: x else: y for array

In [25]:
a = np.arange(20)

In [26]:
np.where(a < 5, a, a * 10)

array([  0,   1,   2,   3,   4,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

#### Logical_and

In [27]:
np.logical_and(True, False)

False

In [28]:
np.logical_and([True, False], [False, False])

array([False, False])

In [29]:
np.logical_and(a > 1, a < 4)

array([False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])